### ISSUE TITLE
Offline Demo and Data loading

### ISSUE THREAD

**Issue by prraoo** [nilavra/vizwiz-captions#1]
Dear @nilavra ,

Thank you for the awesome dataset demo code! It helped me a lot to understand :)

I wanted your aid in modifying the code for two things:

1. Instead of downloading images all the time, how can I modify the code such that it refers to the local path and reads images sequentially from a local folder?

2. Where can I find the json file with captions for Train, Test, and Val images?

Thank you

**Comment by nilavra** [comment]
Hi @raoanonymous ,

Apologies for the delay in getting back to you. 

Development and maintenance responsibilities of this project has been transferred.  Please visit the repository below for obtaining the latest code, and your queries.

[https://github.com/Yinan-Zhao/vizwiz-caption](https://github.com/Yinan-Zhao/vizwiz-caption) 

Thank you.

**Comment by prraoo** [comment]
Okay, thank you :)
